
@extends('website.layout.app')

@section('content')



    <!-- Start About
    ============================================= -->
    <div class="about-area bg-gray services-include default-padding">
        <div class="container">
            <div class="row">
                <div class="col-md-6 default info">
                    <h2>{{ $about->title }}</h2>
                    <p>
                        {{ $about->excerpt }}
                     </p>
                    <p>
                       {!! $about->content !!}                  </p>
                    <div class="bottom-info">
                        <ul>
                            <li>
                                <a class="btn btn-theme effect btn-sm" href="{{ url('contact') }}">contact us</a>
                            </li>
                            <li><i class="fas fa-phone"></i> 01-4155311</li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-6 services text-center">
                    <div class="col-md-6 equal-height">
                        <a href="{{ url('saving') }}">
                            <i class="flaticon-service"></i>
                            <h4>Saving Planning</h4>
                        </a>
                    </div>
                    <div class="col-md-6 equal-height">
                        <a href="{{ url('loan') }}">
                            <i class="flaticon-profits"></i>
                            <h4>Loan Planning</h4>
                        </a>
                    </div>
                    <div class="col-md-6 equal-height">
                        <a href="{{ url('saving') }}">
                            <i class="flaticon-id"></i>
                            <h4>Fixed Saving Planning</h4>
                        </a>
                    </div>
                    <!-- <div class="col-md-6 equal-height">
                        <a href="#">
                            <i class="flaticon-presentation"></i>
                            <h4>Other Support & Planning</h4>
                        </a>
                    </div> -->
                </div>
            </div>
        </div>
    </div>
    <!-- End About -->

    <!-- Start How it Work
    ============================================= -->
    <div class="works-rules-area default-padding">
        <div class="container">
            <div class="row">
                <div class="site-heading text-center">
                    <div class="col-md-8 col-md-offset-2">
                        <h2>Work Process</h2>
                        <p>
                            In Noor Multipurpose cooperative, the work process is characterized by collaborative decision-making, with members actively participating in key choices that impact the organization. Shared ownership and control create an inclusive environment where each member contributes to achieving common goals. The cooperative work process fosters a sense of community, mutual support, and equitable distribution of benefits among its members.                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="works-rules-items">
                    <div class="col-md-3 col-sm-6">
                        <div class="item">
                            <div class="icon">
                                <i class="fas fa-users"></i>
                            </div>
                            <div class="vertical-line">
                                <span>1</span>
                            </div>
                            <div class="info">
                                <h4>Democratic Decision-Making</h4>
                                <p>
                                    The cooperative's working process involves democratic decision-making, where each member has an equal say in key decisions affecting the organization. This ensures that the collective voice of the members guides the cooperative's direction.                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="item">
                            <div class="info">
                                <h4>Equitable Distribution of Benefits</h4>
                                <p>
                                    One of the core principles of cooperatives is the equitable distribution of benefits. Profits and rewards generated by the cooperative are shared among its members, promoting economic fairness and sustainability in the community.                                </p>
                            </div>
                            <div class="vertical-line bottom">
                                <span>2</span>
                            </div>
                            <div class="icon icon-down">
                                <i class="fas fa-file"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="item">
                            <div class="icon">
                                <i class="fas fa-chart-pie"></i>
                            </div>
                            <div class="vertical-line">
                                <span>3</span>
                            </div>
                            <div class="info">
                                <h4>Shared Ownership and Control</h4>
                                <p>
                                    Members actively participate in the ownership and control of the cooperative, fostering a sense of shared responsibility. This cooperative structure encourages a more equitable distribution of power and benefits among all members.                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="item">
                            <div class="info">
                                <h4>Collaborative Work Environment</h4>
                                <p>
                                    The cooperative promotes a collaborative work environment, emphasizing teamwork and mutual support. Members work together to achieve common goals, fostering a sense of community and unity within the organization.                                </p>
                            </div>
                            <div class="vertical-line bottom">
                                <span>4</span>
                            </div>
                            <div class="icon icon-down">
                                <i class="fas fa-chalkboard-teacher"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End How it Work -->

    <!-- Start Our Story
    ============================================= -->
    <div class="our-story-area default-padding bg-gray">
        <div class="container-fluid">
            <div class="row">
                <div class="site-heading text-center">
                    <div class="col-md-8 col-md-offset-2">
                        <h2>{{ $history->title }}</h2>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
               {!! $history->content !!}
            </div>
        </div>
    </div>
    <!-- End Our Story -->

    <!-- Start Business Growth
    ============================================= -->
    <div class="business-groth-area reverse default-padding">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="lineChart">
                        <canvas id="lineChart" height="200"></canvas>
                    </div>
                </div>
                <div class="col-md-6 default info">
                    <h2>Annual Report <br>from starting to now</h2>
                    <p>
                       {!! $annual_report->content !!}
                    </p>
                    <a class="btn btn-theme effect btn-sm" href="{{ url('annual-report') }}">View details</a>
                </div>
            </div>
        </div>
    </div>
    <!-- End Business Growth -->

    <!-- Clients
    ============================================= -->
   @include('website.layout.clients')
    <!-- End Clients -->


@endsection
